name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make g++ cppcheck
      - name: Build
        run: make
      - name: Run tests
        run: make test
      - name: Static analysis
        run: cppcheck --enable=warning --inconclusive --quiet src zathras_lib/src tests/unit
      - name: Upload zathras binary
        uses: actions/upload-artifact@v4
        with:
          name: zathras
          path: zathras
          retention-days: 7
      - name: Upload static library
        uses: actions/upload-artifact@v4
        with:
          name: libzathras
          path: libzathras.a
          retention-days: 7
