name: CI
on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y make g++ cppcheck
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install -y make mingw cppcheck
      - name: Run pipeline
        run: python run.py
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: zathras-${{ runner.os }}
          path: zathras.zip
